#!/usr/bin/env bash

function __git-commit-message_main__() {

local INPUT
local TYPE
local TICK
local MESSAGE

INPUT="$*"

local opts=()
for (( i=0; i <= $#; i++ )); do
  case "$1" in
  --)
    shift
    MESSAGE="$*"
    break
    ;;
  -*)
    opts+=("$1")
    shift
    ;;
  *)
    if [[ -n "$TYPE" ]]; then
      MESSAGE="$TYPE $*"
      opts=()
      unset TYPE
      break
    fi
    TYPE="$(printf '%s' "$1" | \
      grep -Eo '^\w+')"
    TICK="$(printf '%s' "$1" | \
      grep -Eo "$TYPE\(\w+-[0-9]+\)" | \
      tr "[:lower:]" "[:upper:]")"
    shift
    ;;
  esac
done

if [[ -z "$TICK" ]]; then
  local BRANCH
  BRANCH="$(git branch --show-current)"
  if [[ -n "$BRANCH" ]]; then
    TICK="$(printf '%s' "$BRANCH" | \
      grep -Eo '^(\w+/)?(\(\w+[-_][0-9]+\)|\w+[-_][0-9]+)' | \
      grep -Eo '\w+[-_][0-9]+' | \
      tr "[:lower:]" "[:upper:]")"

    if [[ -n "$TICK" ]] && [[ -z "$TYPE" ]]; then
      TYPE="chore"
      echo -e "\n\e[33m\e[1mWARN:\e[0m\e[33m inferring commit type '$TYPE'\e[0m\n" >&2
    fi
  fi
fi

if [[ -n "$TYPE" ]]; then
  local BAD_TYPE
  BAD_TYPE=true
  for type in "${COMMIT_TYPES[@]}"; do
    if [[ "$type" == "$TYPE"* ]]; then
      TYPE="$type"
      BAD_TYPE=false
      break
    fi
  done

  if [[ $BAD_TYPE == true ]]; then
    git commit -m "$INPUT" || return $?
    if [[ -n "$TICK" ]]; then
      local INFO_MSG="\n* types: ${COMMIT_TYPES[@]}"
      echo -e "\n\e[33m\e[1mWARN:\e[0m\e[33m unknown commit type '$TYPE' $INFO_MSG\e[0m" >&2
    fi
  else
    if [[ -z "$TICK" ]]; then
      git commit "${opts[@]}" -m "$TYPE: $MESSAGE"
    else
      git commit "${opts[@]}" -m "$TYPE($TICK): $MESSAGE"
    fi
  fi
else
  if [[ -z "$INPUT" ]]; then
    git commit -e
  else
    git commit -m "$INPUT"
  fi
fi

}

__git-commit-message_main__ "$@"
