#!/usr/bin/env bash

if [ -n "$ZSH_VERSION" ]; then
  setopt +o nomatch
else
  shopt -u nullglob
fi

function push_workspace() {
  if [[ "${WORKSPACE_STACK:-0}" -gt "9" ]]; then
    (( WORKSPACE_STACK=1 ))
  else
    (( WORKSPACE_STACK++ ))
  fi
  eval "WORKSPACE_STACK_$WORKSPACE_STACK=\"$1\""
}

function pop_workspace() {
  if [[ "${WORKSPACE_STACK:-0}" -gt "0" ]]; then
    eval "echo -e \$WORKSPACE_STACK_$WORKSPACE_STACK;unset WORKSPACE_STACK_$WORKSPACE_STACK"
    (( WORKSPACE_STACK-- ))
  else
    echo ""
  fi
}

function __workspace_main__() {

local INFO_MSG="INFO"
local ERROR_MSG="ERROR"

local BRANCH="$1"
local OPERATION="$2"

local GIT_DIR=""
local THIS_BRANCH=""

local WORKSPACE_BRANCH="$WORKSPACE_BRANCH"
local WORKSPACE_ROOT_DIR="$WORKSPACE_ROOT_DIR"
local WORKSPACE_DEFAULT_DIR="$WORKSPACE_DEFAULT_DIR"

GIT_DIR="$(git rev-parse --show-toplevel)"

if [[ -z "$GIT_DIR" ]]; then
  echo "$ERROR_MSG: this script must be run in a git directory" >&2
  return 1
else
  [[ -z "$MSYSTEM" ]] || GIT_DIR="$(cygpath -u "$GIT_DIR")"

  THIS_BRANCH="$(git branch --show-current)"

  for branch in $WORKSPACE_BRANCH staging main master; do
    if [[ -n "$(git show-ref "refs/heads/$branch")" ]]; then
      WORKSPACE_BRANCH="$branch"
      break
    fi
    WORKSPACE_BRANCH=
  done

  if [[ -z "$WORKSPACE_BRANCH" ]]; then
    echo "$ERROR_MSG: could not find default branch" >&2
    return 1
  else
    echo "$INFO_MSG: using '$WORKSPACE_BRANCH' as default branch" >&2
  fi

  case "$BRANCH" in
  "staging"|"main"|"master")
    if ! git show-ref --quiet "refs/heads/$BRANCH"; then
      echo -n "Did you mean default branch '$WORKSPACE_BRANCH'? [Y/n] "
      read -r MEANT_WORKSPACE_BRANCH
      if [[ -z "${MEANT_WORKSPACE_BRANCH#[Yy]}" ]]; then
        BRANCH="$WORKSPACE_BRANCH"
      fi
    fi
    ;;
  "-")
    BRANCH="$(pop_workspace)"
    ;;
  ".")
    BRANCH="$THIS_BRANCH"
    ;;
  "")
    BRANCH="$WORKSPACE_BRANCH"
    ;;
  *)
    ;;
  esac

  if [[ $BRANCH =~ ^[^-.\ /[:alnum:]]+$ ]]; then
    echo "$ERROR_MSG: invalid parameter '$BRANCH'" >&2
    return 1
  fi

  push_workspace "$THIS_BRANCH"

  if [[ -z "$WORKSPACE_ROOT_DIR" ]]; then
    if [[ -z "$WORKSPACE_DEFAULT_DIR" ]]; then
      WORKSPACE_DEFAULT_DIR="$(git worktree list --porcelain | \
        grep "^worktree .*$WORKSPACE_BRANCH$" | \
        cut -d' ' -f2)"
    fi
    if [[ -n "$WORKSPACE_DEFAULT_DIR" ]]; then
        [[ -z "$MSYSTEM" ]] || WORKSPACE_DEFAULT_DIR="$(cygpath -u "$WORKSPACE_DEFAULT_DIR")"
        WORKSPACE_ROOT_DIR="${WORKSPACE_DEFAULT_DIR%/"$WORKSPACE_BRANCH"}"
    fi
  fi
  if [[ -z "$WORKSPACE_ROOT_DIR" || -n "$WORKSPACE_DEFAULT_DIR" && ! -d "$WORKSPACE_ROOT_DIR/$THIS_BRANCH" ]]; then
    WORKSPACE_ROOT_DIR="$(dirname "$PWD")/ws-$(basename "$PWD")"
  else
    echo "$INFO_MSG: found workspace root at '$WORKSPACE_ROOT_DIR'" >&2
  fi

  if [[ ! -d "$WORKSPACE_ROOT_DIR" ]]; then
    if [[ -t 0 ]]; then
      echo -n "Initialize default workspace at '$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH'? [Y/n] "
      read -r DO_CREATE_WORKSPACE
      if [[ -n "${DO_CREATE_WORKSPACE#[Yy]}" ]]; then
        return 0
      fi
    else
      echo "$INFO_MSG: initializing default workspace at '$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH'" >&2
    fi
    mkdir -p "$WORKSPACE_ROOT_DIR/$(dirname "$WORKSPACE_BRANCH")"
    cp -r "$GIT_DIR" "$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH"
    pushd "$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH" >/dev/null || return 1
    git switch "$WORKSPACE_BRANCH"
    popd >/dev/null || return 1
  else
    pushd "$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH" >/dev/null || return 1
    git worktree prune
    popd >/dev/null || return 1
  fi
fi

if [[ "$OPERATION" != "--" && ! -d "$WORKSPACE_ROOT_DIR/$BRANCH" ]]; then
  if [[ -n "$OPERATION" ]]; then
    echo "$ERROR_MSG: cannot perform operation '$OPERATION'"
    return 1
  fi
  if [[ -n "$WORKSPACE_DEFAULT_DIR" ]]; then
    if [[ -t 0 ]]; then
      # confirm intent if WORKSPACE_ROOT_DIR was guessed
      echo -n "Create workspace at '$WORKSPACE_ROOT_DIR/$BRANCH'? [Y/n] "
      read -r DO_CREATE_WORKSPACE
      if [[ -n "${DO_CREATE_WORKSPACE#[Yy]}" ]]; then
        return 0
      fi
    else
      echo "$INFO_MSG: creating workspace at '$WORKSPACE_ROOT_DIR/$BRANCH'" >&2
    fi
  fi

  pushd "$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH" >/dev/null || return 1
  git worktree repair

  if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
    echo "$INFO_MSG: found local branch '$BRANCH'" >&2
    git worktree add "$WORKSPACE_ROOT_DIR/$BRANCH" "$BRANCH"
  else
    if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null; then
      echo "$INFO_MSG: found remote branch '$BRANCH'" >&2
      git fetch origin "$BRANCH"
      git worktree add "$WORKSPACE_ROOT_DIR/$BRANCH" "$BRANCH"
    else
      echo "$INFO_MSG: creating new branch '$BRANCH'" >&2
      git worktree add --track -b "$BRANCH" "$WORKSPACE_ROOT_DIR/$BRANCH"
    fi
  fi
  popd >/dev/null || return 1

  if [[ -d "$WORKSPACE_DEFAULT_DIR/.scripts" ]]; then
    cp -r "$WORKSPACE_DEFAULT_DIR/.scripts" "$WORKSPACE_ROOT_DIR/$BRANCH/.scripts"

    echo "$INFO_MSG: initialized workspace scripts" >&2
  fi

  if [[ -d "$WORKSPACE_DEFAULT_DIR/.nvim" ]]; then
    cp -r "$WORKSPACE_DEFAULT_DIR/.nvim" "$WORKSPACE_ROOT_DIR/$BRANCH/.nvim"

    if [[ -f "$WORKSPACE_ROOT_DIR/$BRANCH/.nvim/workspace.vim" ]]; then
      true > "$WORKSPACE_ROOT_DIR/$BRANCH/.nvim/workspace.vim"
    fi

    echo "$INFO_MSG: initialized nvim workspace" >&2
  fi

  for init_script in "$WORKSPACE_ROOT_DIR/$BRANCH/.scripts"/init-*.sh; do
    [[ -f "$init_script" ]] && sh "$init_script"
  done

  cd "$WORKSPACE_ROOT_DIR/$BRANCH" || return 1

  for init_script in ~/.dotfiles/scripts/workspace-init-*.sh; do
    [[ -f "$init_script" ]] && sh "$init_script"
  done

  echo "$INFO_MSG: created workspace at '$WORKSPACE_ROOT_DIR/$BRANCH'" >&2
else
  if [[ -n "$OPERATION" ]]; then
    for (( i=1; i <= $#; i++ )); do
      case "$OPERATION" in
      "clean")
        eval BRANCH="\${$i}"
        if [[ $BRANCH =~ ^[-.\ /[:alnum:]]+$ ]]; then
          if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null; then
            echo "$INFO_MSG: can't remove branch '$BRANCH'" >&2
          else
            echo -n "Clean up workspace at '$WORKSPACE_ROOT_DIR/$BRANCH'? [Y/n] "
            read -r DO_CLEAN_WORKSPACE
            if [[ -z "${DO_CLEAN_WORKSPACE#[Yy]}" ]]; then
              cd "$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH" >/dev/null || return 1
              rm -rf "$WORKSPACE_ROOT_DIR/${BRANCH:?}"
              git worktree prune
              git branch --delete "$BRANCH" >/dev/null
              echo "$INFO_MSG: removed workspace at '$WORKSPACE_ROOT_DIR/$BRANCH'" >&2
            fi
          fi
        fi
        [[ $i == 1 ]] && return 0
        ;;
      "--")
        OPERATION="$1"
        shift
        ;;
      *)
        echo "$ERROR_MSG: unknown operation '$OPERATION'"
        return 1
        ;;
      esac
    done
  else
    pushd "$WORKSPACE_ROOT_DIR/$WORKSPACE_BRANCH" >/dev/null || return 1
    git worktree repair
    popd >/dev/null || return 1

    echo "$INFO_MSG: found workspace at '$WORKSPACE_ROOT_DIR/$BRANCH'" >&2

    cd "$WORKSPACE_ROOT_DIR/$BRANCH" || return 1
    git worktree repair
  fi
fi

}

__workspace_main__ "$@"

unset -f push_workspace
unset -f pop_workspace
