{{- if (index . "gitlab") }}
[".ssh/keys"]
  type = "archive"
  url = "https://gitlab.com/api/v4/projects/26349363/repository/archive?private_token={{ .gitlab.token }}"
  exact = true
  stripComponents = 1
{{- end }}

## Windows
{{- $exe := "exe" }}
{{- $alacritty := "Alacritty-v[0-9.]+-portable" }}
{{- $nvim := "nvim-win64" }}
{{- $fd := "fd-v[0-9.]+-x86_64-pc-windows-msvc" }}
{{- $rg := "ripgrep-[0-9.]+-x86_64-pc-windows-msvc" }}
## Darwin
{{- if eq .chezmoi.os "darwin" }}
{{-   $exe = "dmg" }}
{{-   $alacritty = "Alacritty-v[0-9.]+" }}
{{-   $nvim = "nvim-macos" }}
{{-   $fd = "fd-v[0-9.]+-x86_64-apple-darwin" }}
{{-   $rg = "ripgrep-[0-9.]+-x86_64-apple-darwin" }}
{{- end }}

[".dotfiles/deps/nvim/.local"]
  type = "archive"
  url = "https://github.com/neovim/neovim/releases/latest/download/{{ $nvim }}.zip"
  exact = true
  stripComponents = 1

[".dotfiles/deps/fd/.local/bin"]
  type = "archive"
  url = "https://glare.now.sh/sharkdp/fd/{{ $fd }}[.]zip"
  exact = true
  stripComponents = 1

[".dotfiles/deps/rg/.local/bin"]
  type = "archive"
  url = "https://glare.now.sh/BurntSushi/ripgrep/{{ $rg }}[.]zip"
  exact = true
  stripComponents = 1

[".dotfiles/deps/hack-nf/.local/share/fonts"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip"

[".dotfiles/deps/alacritty/.local/bin/alacritty.{{ $exe }}"]
  type = "file"
  url = "https://glare.now.sh/alacritty/alacritty/{{ $alacritty }}[.]{{ $exe }}"
  executable = true
