{{ $isWindows := eq .chezmoi.os "windows" }}

{{- define "dep" }}
{{- $path := . }}
[{{ printf ".dotfiles/deps/%s" $path | quote }}]
  exact = true
  exclude = ["**/CHANGELOG*", "**/COPYING*", "**/dll", "**/doc", "**/example", "**/include", "**/*LICENSE*", "**/licenses", "**/README*", "**/static"]
{{- end }}

{{- if index . "gitlab" }}
[".ssh/keys"]
  url = "https://gitlab.com/n0brain3r/dotfiles-ssh-keys/-/archive/master/dotfiles-ssh-keys-master.zip?private_token={{ .gitlab.token }}"
  type = "archive"
  stripComponents = 1
{{- end }}

[".dotfiles/tree-sitter-nim"]
  url = "https://github.com/aMOPel/tree-sitter-nim/archive/refs/heads/main.zip"
  type = "archive"
  stripComponents = 1

[".dotfiles/tree-sitter-norg"]
  url = "https://github.com/nvim-neorg/tree-sitter-norg/archive/refs/heads/main.zip"
  type = "archive"
  stripComponents = 1

{{ template "dep" "neovim/.local" }}
  {{- if $isWindows }}
  url = "https://github.com/neovim/neovim/releases/download/stable/nvim-win64.zip"
  {{- else }}
  url = "https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz"
  {{- end}}
  type = "archive"
  stripComponents = 1

{{ template "dep" "nerd-fonts/.local/share/fonts" }}
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"
  type = "archive"

{{ template "dep" "starship/.local/bin" }}
  {{- if $isWindows }}
  url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-pc-windows-msvc.zip"
  {{- else }}
  url = "https://github.com/starship/starship/releases/latest/download/starship-aarch64-apple-darwin.tar.gz"
  {{- end }}
  type = "archive"

{{ template "dep" "fd/.local/bin" }}
  {{- if $isWindows }}
  url = "https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-pc-windows-msvc.zip"
  {{- else}}
  url = "https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-apple-darwin.tar.gz"
  {{- end }}
  type = "archive"
  stripComponents = 1

{{ template "dep" "ripgrep/.local/bin" }}
  {{- if $isWindows }}
  url = "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-pc-windows-msvc.zip"
  {{- else }}
  url = "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-apple-darwin.tar.gz"
  {{- end }}
  type = "archive"
  stripComponents = 1

{{- if $isWindows }}
{{ template "dep" "alacritty/.local/bin/alacritty.exe" }}
  url = "https://github.com/alacritty/alacritty/releases/download/v0.12.1/Alacritty-v0.12.1-portable.exe"
  type = "file"
  executable = true

{{ template "dep" "alacritty/.config/alacritty/catppuccin" }}
  url = "https://github.com/catppuccin/alacritty/archive/refs/heads/main.zip"
  type = "archive"
  stripComponents = 1

{{ template "dep" "jq/.local/bin/jq.exe" }}
  url = "https://github.com/jqlang/jq/releases/latest/download/jq-win64.exe"
  type = "file"
  executable = true

{{ template "dep" "zsh/zsh.pkg.tar.zst" }}
  url = "https://mirror.msys2.org/msys/x86_64/zsh-5.9-2-x86_64.pkg.tar.zst"
  type = "file"

{{ template "dep" "zstd/.local/bin" }}
  url = "https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-v1.5.5-win64.zip"
  type = "archive"
  stripComponents = 1
{{- end }}
