{{- if (index . "gitlab") }}
[".ssh/keys"]
  url = "https://gitlab.com/api/v4/projects/26349363/repository/archive?private_token={{ .gitlab.token }}"
  type = "archive"
  exact = true
  stripComponents = 1
{{- end }}

{{ $isWindows := eq .chezmoi.os "windows" }}

{{- define "github.com/releases" }}
{{- $match := index . 0 }}
{{- $owner := index . 1 }}
{{- $query := ".assets[] | select(.name | contains(\"%s\")) | .browser_download_url" }}
{{- $info := (gitHubLatestRelease $owner) | toJson | fromJsonc }}
{{- $url := $info | jq (printf $query $match) | first }}
url = {{ $url | quote }}
{{- end }}

[".dotfiles/deps/nvim/.local"]
  {{ template "github.com/releases" "neovim/neovim"
    | list ($isWindows | ternary
      "win64.zip"
      "macos.tar.gz") }}
  type = "archive"
  exact = true
  stripComponents = 1

[".dotfiles/deps/cascadiacode-nf/.local/share/fonts"]
  {{ template "github.com/releases" "ryanoasis/nerd-fonts"
    | list "CascadiaCode.zip" }}
  type = "archive"
  exact = true

[".dotfiles/deps/catppuccin/.config/alacritty/catppuccin"]
  url = "https://github.com/catppuccin/alacritty/archive/refs/heads/main.zip"
  type = "archive"
  exact = true
  stripComponents = 1

[".dotfiles/deps/starship/.local/bin"]
  {{ template "github.com/releases" "starship/starship"
    | list ($isWindows | ternary
      "x86_64-pc-windows-msvc.zip"
      "x86_64-apple-darwin.tar.gz") }}
  type = "archive"
  exact = true

[".dotfiles/deps/fd/.local/bin"]
  {{ template "github.com/releases" "sharkdp/fd"
    | list ($isWindows | ternary
      "x86_64-pc-windows-msvc.zip"
      "x86_64-apple-darwin.tar.gz") }}
  type = "archive"
  exact = true
  stripComponents = 1

[".dotfiles/deps/rg/.local/bin"]
  {{ template "github.com/releases" "BurntSushi/ripgrep"
    | list ($isWindows | ternary
      "x86_64-pc-windows-msvc.zip"
      "x86_64-apple-darwin.tar.gz") }}
  type = "archive"
  exact = true
  stripComponents = 1

{{- if $isWindows }}
[".dotfiles/deps/alacritty/.local/bin/alacritty.exe"]
  {{ template "github.com/releases" "alacritty/alacritty"
    | list "portable.exe" }}
  type = "file"
  executable = true

[".dotfiles/deps/jq/.local/bin/jq.exe"]
  {{ template "github.com/releases" "stedolan/jq"
    | list "jq-win64.exe" }}
  type = "file"
  executable = true
{{- end }}
