{{- if (index . "gitlab") }}
[".ssh/keys"]
  type = "archive"
  url = "https://gitlab.com/api/v4/projects/26349363/repository/archive?private_token={{ .gitlab.token }}"
  exact = true
  stripComponents = 1
{{- end }}

## Windows
{{- $nvim := "nvim-win64.zip" }}
{{- $fd := "fd-v[0-9.]+-x86_64-pc-windows-msvc[.]zip" }}
{{- $rg := "ripgrep-[0-9.]+-x86_64-pc-windows-msvc[.]zip" }}
{{- $starship := "starship-x86_64-pc-windows-msvc.zip" }}
## Darwin
{{- if eq .chezmoi.os "darwin" }}
{{-   $nvim = "nvim-macos.tar.gz" }}
{{-   $fd = "fd-v[0-9.]+-x86_64-apple-darwin[.]tar[.]gz" }}
{{-   $rg = "ripgrep-[0-9.]+-x86_64-apple-darwin[.]tar[.]gz" }}
{{-   $starship := "starship-x86_64-apple-darwin.tar.gz" }}
{{- end }}

[".dotfiles/deps/nvim/.local"]
  type = "archive"
  url = "https://github.com/neovim/neovim/releases/latest/download/{{ $nvim }}"
  exact = true
  stripComponents = 1

[".dotfiles/deps/fd/.local/bin"]
  type = "archive"
  url = "https://glare.now.sh/sharkdp/fd/{{ $fd }}"
  exact = true
  stripComponents = 1

[".dotfiles/deps/rg/.local/bin"]
  type = "archive"
  url = "https://glare.now.sh/BurntSushi/ripgrep/{{ $rg }}"
  exact = true
  stripComponents = 1

[".dotfiles/deps/starship/.local/bin"]
  type = "archive"
  url = "https://github.com/starship/starship/releases/latest/download/{{ $starship }}"
  exact = true

[".dotfiles/deps/cascadiacode-nf/.local/share/fonts"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"

{{- if eq .chezmoi.os "windows" }}
[".dotfiles/deps/broot/.local/bin/broot.exe"]
  type = "file"
  url = "https://dystroy.org/broot/download/x86_64-pc-windows-gnu/broot.exe"
  executable = true

[".dotfiles/deps/jq/.local/bin/jq.exe"]
  type = "file"
  url = "https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe"
  executable = true

[".dotfiles/deps/alacritty/.local/bin/alacritty.exe"]
  type = "file"
  url = "https://glare.now.sh/alacritty/alacritty/Alacritty-v[0-9.]+-portable[.]exe"
  executable = true
{{- end }}
