{{- if (index . "gitlab") }}
[".ssh/keys"]
  type = "archive"
  url = "https://gitlab.com/api/v4/projects/26349363/repository/archive?private_token={{ .gitlab.token }}"
  exact = true
  stripComponents = 1
{{- end }}

[".dotfiles/fonts"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"
  exact = true
  refreshPeriod = "168h"

{{- $nvim := "" }}
{{- $fd := "" }}
{{- $rg := "" }}
{{- if eq .chezmoi.os "windows" }}
{{-   $nvim = "nvim-win64" }}
{{-   $fd = "v8.3.1/fd-v8.3.1-x86_64-pc-windows-msvc" }}
{{-   $rg = "13.0.0/ripgrep-13.0.0-x86_64-pc-windows-msvc" }}
{{- else if eq .chezmoi.os "darwin" }}
{{-   $nvim = "nvim-macos" }}
{{-   $fd = "v8.3.1/fd-v8.3.1-x86_64-apple-darwin" }}
{{-   $rg = "13.0.0/ripgrep-13.0.0-x86_64-apple-darwin" }}
{{- end }}

[".dotfiles/nvim"]
  type = "archive"
  url = "https://github.com/neovim/neovim/releases/latest/download/{{ $nvim }}.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".dotfiles/fd"]
  type = "archive"
  url = "https://github.com/sharkdp/fd/releases/download/{{ $fd }}.zip"
  exact = true
  stripComponents = 1

[".dotfiles/rg"]
  type = "archive"
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ $rg }}.zip"
  exact = true
  stripComponents = 1
