{{- if (index . "gitlab") }}
[".ssh/keys"]
  type = "archive"
  url = "https://gitlab.com/api/v4/projects/26349363/repository/archive?private_token={{ .gitlab.token }}"
  exact = true
  stripComponents = 1
{{- end }}

[".dotfiles/fonts"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"
  exact = true

{{- $nvim := "" }}
{{- $fd := "" }}
{{- $rg := "" }}
{{- if eq .chezmoi.os "windows" }}
{{-   $nvim = "nvim-win64" }}
{{-   $fd = "fd-v[0-9.]+-x86_64-pc-windows-msvc" }}
{{-   $rg = "ripgrep-[0-9.]+-x86_64-pc-windows-msvc" }}
{{- else if eq .chezmoi.os "darwin" }}
{{-   $nvim = "nvim-macos" }}
{{-   $fd = "fd-v[0-9.]+-x86_64-apple-darwin" }}
{{-   $rg = "ripgrep-[0-9.]+-x86_64-apple-darwin" }}
{{- end }}

[".dotfiles/deps/nvim/.local"]
  type = "archive"
  url = "https://github.com/neovim/neovim/releases/latest/download/{{ $nvim }}.zip"
  exact = true
  stripComponents = 1

[".dotfiles/deps/fd/.local/bin"]
  type = "archive"
  url = "https://glare.now.sh/sharkdp/fd/{{ $fd }}[.]zip"
  exact = true
  stripComponents = 1

[".dotfiles/deps/rg/.local/bin"]
  type = "archive"
  url = "https://glare.now.sh/BurntSushi/ripgrep/{{ $rg }}[.]zip"
  exact = true
  stripComponents = 1
