-- vim: fcl=all fdm=marker fdl=0 fen

local opt = vim.opt

my_options {
  background = "dark",
  belloff = "all",
  opt.clipboard + "unnamed,unnamedplus",
  cmdheight = 0,
  confirm = true,
  cursorline = true,
  cursorlineopt = "number",
  opt.display + "lastline,uhex",
  equalalways = true,
  expandtab = true,
  fillchars = { --{{{
    eob = " ",
    fold = " ",
    foldopen = "┯",
    foldsep = "│",
    foldclose = "󰐕",
    stl = " ",
  }, --}}}
  foldcolumn = '1',
  foldenable = true,
  foldlevelstart = 99,
  foldmethod = "indent",
  grepprg = [[rg --no-heading --no-messages --vimgrep --ignore-file="$HOME/.dotfiles/rgignore/main" --ignore-file="$HOME/.dotfiles/rgignore/$NVIM_PROJECT_TYPE" --ignore-file="$PWD/.nvim/ignore"]],
  grepformat = "%f:%l:%c:%m",
  guicursor = { --{{{
    "v-n-sm:block",
    "i-c-ci-ve:ver25",
    "r-cr:hor20",
    "o:hor20-blinkwait0-blinkon400-blinkoff250",
  }, --}}}
  hidden = true,
  hlsearch = false,
  ignorecase = true,
  isfname = "@,48-57,/,\\,.,-,_,+,,,#,$,%,~,=",
  isident = "@,48-57,_,192-255",
  laststatus = 3,
  linebreak = true,
  list = true,
  opt.listchars + { --{{{
    multispace = "· ",
    tab = "▸ ",
  }, --}}}
  mouse = "a",
  number = true,
  numberwidth = 2,
  quickfixtextfunc = 'v:lua.fn.qf_text',
  ruler = false,
  scrollback = 9001,
  scrolloff = 3,
  sessionoptions = "buffers,folds,winsize,winpos",
  shiftwidth = 2,
  opt.shortmess + "acsCFISW",
  showbreak = "↪",
  showcmd = false,
  showmode = false,
  showtabline = 0,
  signcolumn = "yes",
  smartcase = true,
  smartindent = true,
  spell = false,
  splitbelow = true,
  splitkeep = 'screen',
  splitright = true,
  tabstop = 2,
  termguicolors = true,
  timeoutlen = 400,
  title = true,
  titlestring = [[%{fnamemodify(v:lua.fn.get_workspace_dir(), ":t")} - %{v:lua.fn.get_buffer_title()}]],
  undofile = true,
  updatetime = 500,
  virtualedit = "onemore",
  opt.whichwrap + "<>[]hl",
  wrap = true,
}
