#!/usr/bin/env bash

source ~/.dotfiles/envrc
source ~/.dotfiles/shellrc

_GIT_EXEC_PATH="$(git --exec-path 2>/dev/null)"
_GIT_COMPLETION_PATH="${_GIT_EXEC_PATH%/libexec/git-core}"
_GIT_COMPLETION_PATH="${_GIT_COMPLETION_PATH%/lib/git-core}"
_GIT_COMPLETION_PATH="$_GIT_COMPLETION_PATH/share/git/completion"

if [ -f "$_GIT_COMPLETION_PATH/git-completion.bash" ]; then
  source "$_GIT_COMPLETION_PATH/git-completion.bash"
fi

bind 'set show-all-if-ambiguous on'
bind 'set completion-ignore-case off'

bind 'TAB:menu-complete'
bind '"\e[Z":menu-complete-backward'
bind "set menu-complete-display-prefix on"

bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=$HISTSIZE

PROMPT_COMMAND="history -a $HISTFILE;$PROMPT_COMMAND"

__git_complete g __git_main
__git_complete cg __git_main

function _workspace() {
  COMPREPLY=()
  if command git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    local locals="$(command git for-each-ref \
      --sort=-committerdate \
      --format='%(refname:lstrip=2)' \
      refs/heads/)"
    local current="$(command git branch --show-current)"
    local workspaces="$(echo -e "$locals" | grep -v HEAD | grep -v "$current")"
    COMPREPLY=($(compgen -W "$workspaces" -- "${COMP_WORDS[1]}"))
  fi
}

complete -o nosort -F _workspace workspace
complete -o nosort -F _workspace ws

[ -f ~/.bashrc ] && source ~/.bashrc

eval "$(starship init bash)"
