#!/usr/bin/env bash

source ~/.dotfiles/envrc
source ~/.dotfiles/shellrc

source "$HOME/.dotfiles/deps/fzf-shell/.local/share/fzf/completion.bash"
source "$HOME/.dotfiles/deps/fzf-shell/.local/share/fzf/key-bindings.bash"

bind 'set show-all-if-ambiguous on'
bind 'set completion-ignore-case off'

bind 'TAB:menu-complete'
bind '"\e[Z":menu-complete-backward'
bind "set menu-complete-display-prefix on"

bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=$HISTSIZE

PROMPT_COMMAND="history -a $HISTFILE;$PROMPT_COMMAND"

complete -F _fzf_complete_workspace -o nosort -o default -o bashdefault workspace
complete -F _fzf_complete_ws -o nosort -o default -o bashdefault ws
complete -F _fzf_complete_w -o nosort -o default -o bashdefault w

if [[ -f ~/.bashrc ]] && ! (return 0 2>/dev/null); then
  source ~/.bashrc
fi

eval "$(starship init bash)"
