[directory]
  disabled = true

[fossil_branch]
  disabled = true

[git_branch]
  disabled = true

[git_commit]
  disabled = true

[git_state]
  disabled = true

[git_metrics]
  disabled = true

[git_status]
  disabled = true

[hg_branch]
  disabled = true

[nim]
  symbol = ' '

[pijul_channel]
  disabled = true

[line_break]
  disabled = true

[vcsh]
  disabled = true

[package]
  disabled = true
