imports = [ "~/.config/broot/base.toml" ]

[special-paths]
  "**/*.iml" = "hide"
  "**/.dart_tool" = "hide"
  "**/.flutter-plugins" = "hide"
  "**/.flutter-plugins-dependencies" = "hide"
  "**/.idea" = "hide"
  "**/.metadata" = "hide"
  "**/android/app" = "hide"
  "**/android/gradle" = "hide"
  "**/android/gradlew" = "hide"
  "**/android/gradlew.bat" = "hide"
  "**/build" = "no-enter"
  "**/doc" = "no-enter"
  "**/.fvm" = "hide"
  "**/ios/Flutter" = "hide"
  "**/ios/Runner" = "hide"
  "**/ios/RunnerTests" = "hide"
  "**/linux" = "hide"
  "**/macos" = "hide"
  "**/pubspec.lock" = "hide"
  "**/windows" = "hide"
  "**/web" = "hide"
