capture_mouse = false
default_flags = "ht"
max_panels_count = 1
show_selection_mark = true
syntax_theme = "MochaDark"

[[verbs]]
  invocation = "edit"
  key = "enter"
  external = 'nvim --server $NVIM --remote-send "<C-\><C-N>:e {file}<CR>"'
  apply_to = "file"

[[verbs]]
  invocation = "vsplit"
  key = "alt-\\"
  external = 'nvim --server $NVIM --remote-send "<C-\><C-N>:vs {file}<CR>"'
  apply_to = "file"

[[verbs]]
  invocation = "split"
  key = "alt-="
  external = 'nvim --server $NVIM --remote-send "<C-\><C-N>:sp {file}<CR>"'
  apply_to = "file"

[[verbs]]
  key = "alt-6"
  execution = ":back"
  leave_broot = false

[[verbs]]
  key = "alt-backspace"
  internal = "input_clear"
  leave_broot = false

[special-paths]
  "**/.git" = "no-enter"
